// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
import SpotifySearchController from "./spotify_search_controller"
import EmotionFilterController from "./emotion_filter_controller"

application.register("hello", HelloController)
application.register("spotify-search", SpotifySearchController)
application.register("emotion-filter", EmotionFilterController)
