// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

// 既存のコントローラーを手動で登録
import HelloController from "./hello_controller"
import SpotifyAutocompleteController from "./spotify_autocomplete"
import SpotifyInputController from "./spotify_input"
import SpotifyModalController from "./spotify_modal"
import SpotifySearchController from "./spotify_search_controller"

application.register("hello", HelloController)
application.register("spotify-autocomplete", SpotifyAutocompleteController)
application.register("spotify-input", SpotifyInputController)
application.register("spotify-modal", SpotifyModalController)
application.register("spotify-search", SpotifySearchController)
