// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

// コントローラーを個別にインポート
import HelloController from "./hello_controller.js"
import SpotifyAutocompleteController from "./spotify_autocomplete.js"
import SpotifyInputController from "./spotify_input.js"
import SpotifyModalController from "./spotify_modal.js"
import SpotifySearchController from "./spotify_search_controller.js"

// コントローラーを登録
application.register("hello", HelloController)
application.register("spotify-autocomplete", SpotifyAutocompleteController)
application.register("spotify-input", SpotifyInputController)
application.register("spotify-modal", SpotifyModalController)
application.register("spotify-search", SpotifySearchController)

// コントローラーの読み込みが完了したことをコンソールに表示
console.log("Stimulus controllers loaded")